config/routes.rb
Rails.application.routes.draw do
  resources :forms
  get "forms/savedForms/:title", to: "forms#title" ,  as: "getForm"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
    has_attached_file :image, styles: { large:"600x600>" , medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates :title, :phone, :name, :image, presence: true
    validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    # @form = Form.find_by(title: params[:title])
  end

  def title
    print("herehrererssssssssssssssssssssssssssssssssssse")
    @form = Form.find_by(title: params[:title])
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to getForm_url(@form.title), notice: 'Form was successfully created.' }
        format.json { render :index, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to getForm_url(@form.title), notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:title, :paragraph, :email, :phone, :propertyType , :image , :jobTitle , :bestTime , :header , :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: form, local: true , html: { multipart: true }) do |form| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
        <% @form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image%>
  </div>

  <div class="field">
    <%= form.label :"Form title" %>
    <%= form.text_field :title , required: true%>
  </div>
    <div class="field">
    <%= form.label :HeadLine %>
    <%= form.text_field :header , required: true %>
  </div>
  

  <div class="field">
    <%= form.label :Description %>
    <%= form.text_area :paragraph , required: true %>
  </div>
   <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone , required: true%>
  </div>

   <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name , required: true%>
  </div>



  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

 
  <div class="field">
    <%= form.label :"Best Time To call" %>
    <%= form.text_field :bestTime %>
  </div>
  <div class="field">
    <%= form.label :"Job Title" %>
    <%= form.text_field :jobTitle %>
  </div>

  <div class="field">
    <%= form.label :"Property Type" %>
    <%= form.select(:propertyType, ["None" , "Villa" , "Apartment" , "Townhouse" , "Twinhouse"], {}, {class: "form-control"} ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', getForm_url(@form.title)%> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Propertytype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.title %></td>
        <td><%= form.name %></td>
        <td><%= form.email %></td>
        <td><%= form.phone %></td>
        <td><%= form.propertyType %></td>
        <td><%= link_to 'Show', getForm_url(form.title) %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "center">
  <%= image_tag @form.image.url(:large)%>

  <h1><%= @form.propertyType if @form.propertyType != "None"%></h1>
  <h1><%= @form.header%></h1>
  <h5> <%= @form.paragraph %></h5>

   
<%= form_with(model: @form, local: true , html: { multipart: true }) do |form| %>
 
  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :name%>
  </div>
  <div class="field">
    <%= form.label :email if @form.email.chars.length > 0%>
    <%= form.text_field :email if @form.email.chars.length > 0%>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  <div class="field">
    <%= form.label :"Best Time To call" if @form.bestTime.chars.length > 0%>
    <%= form.text_field :bestTime if @form.bestTime.chars.length > 0%>
  </div>
  <div class="field">
    <%= form.label :"Job Title" if @form.jobTitle.chars.length > 0%>
    <%= form.text_field :jobTitle if @form.jobTitle.chars.length > 0%>
  </div>
<%end%>





<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>
     </div>
<style>
.center {
  margin: auto;
  width: 38%;
  /* border: 1px solid #73AD21; */
  padding: 10px;
}
</style>

app/views/forms/title.html.erb
<p id="notice"><%= notice %></p>
<div class = "center">
  <%= image_tag @form.image.url(:large)%>

  <h1><%= @form.propertyType if @form.propertyType != "None"%></h1>
  <h1><%= @form.header%></h1>
  <h5> <%= @form.paragraph %></h5>

   
<%= form_with(model: @form, local: true , html: { multipart: true }) do |form| %>
 
  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field "" , placeholder: @form.name %>
  </div>
  <div class="field">
    <%= form.label :email if @form.email.chars.length > 0%>
    <%= form.text_field "" , placeholder: @form.email  if @form.email.chars.length > 0%>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field "" ,  placeholder: @form.phone%>
  </div>
  <div class="field">
    <%= form.label :"Best Time To call" if @form.bestTime.chars.length > 0%>
    <%= form.text_field "", placeholder: @form.bestTime  if @form.bestTime.chars.length > 0%>
  </div>
  <div class="field">
    <%= form.label :"Job Title" if @form.jobTitle.chars.length > 0%>
    <%= form.text_field "" , placeholder: @form.jobTitle  if @form.jobTitle.chars.length > 0%>
  </div>
<%end%>





<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>
     </div>
<style>
.center {
  margin: auto;
  width: 38%;
  /* border: 1px solid #73AD21; */
  padding: 10px;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoolingTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>